version: '3.8'
services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: travel_node
      MYSQL_ROOT_PASSWORD: jystella
    ports:
      - 3306:3306

  backend:
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/travel_node
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: jystella
    ports:
      - 8080:8080
    depends_on:
      - mysqldb